using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VehicleLib.Errors
{
	/// <summary>
	///  An exception generated by a vehicle.
	///  Because javascript is not capable of generating a proper exception, a JSON object containing a vehicle exception is thrown
	///  This is the base class for all vehicle exceptions
	/// </summary>
	[Serializable]
	public class Error
	{
		private string _message;

		public string Message
		{
			get { return _message; }
		}

		
		public Error() {} // consider making default private and exposing to JSON deserializartio only

		public Error(string message)
		{
			_message = message;
		}
	}
}
